# Site settings
title: dumpling
email: EMAILyouremailaddress@gmail.com
description: The FIVE Jekyll version of the Identity theme by HTML5 UP.
baseurl: "/identity-jekyll-theme" # the subpath of your site, e.g. /blog
url: "https://github.com/adzk" # the base hostname & protocol for your site

# Identity
your-name: lakjflakjf
your-title: Spaghetti and meetballs

# Social settings
500px_url:
# facebook_url: https://facebook.com
github_url: https://github.com/adzk
# gitlab_url: https://gitlab.com/u/andrewbanchich
# googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
# instagram_url: https://instagram.com
# linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
# pinterest_url:
# slack_url:
# twitter_url: https://twitter.com/andrewbanchich

# Build settings
markdown: kramdown
